name: queue_up_india
description: QueueUp gaming squad finder app foundation.
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^16.3.0
  get_it: ^8.2.0
  google_fonts: ^6.3.1
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.1.3
  cloud_functions: ^6.0.7
  audioplayers: ^6.1.0
  vibration: ^2.0.1
  firebase_messaging: ^16.1.2
  firebase_crashlytics: ^5.0.0
  flutter_local_notifications: ^21.0.0
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  device_info_plus: ^11.2.0
  connectivity_plus: ^7.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/rank_png/
    - assets/pubg/
    - assets/logos/
    - assets/freefire/
    - assets/ringtone/
