import 'package:equatable/equatable.dart';

class CountryCodeOption extends Equatable {
  const CountryCodeOption({required this.isoCode, required this.name, required this.dialCode});

  final String isoCode;
  final String name;
  final String dialCode;

  String get id => '${isoCode}|${dialCode}';
  String get label => '${dialCode} ${name}';

  @override
  List<Object?> get props => <Object?>[isoCode, name, dialCode];
}

const List<CountryCodeOption> countryCodeOptions = <CountryCodeOption>[
  CountryCodeOption(isoCode: 'AF', name: 'Afghanistan', dialCode: '+93'),
  CountryCodeOption(isoCode: 'AX', name: 'Aland Islands', dialCode: '+358'),
  CountryCodeOption(isoCode: 'AL', name: 'Albania', dialCode: '+355'),
  CountryCodeOption(isoCode: 'DZ', name: 'Algeria', dialCode: '+213'),
  CountryCodeOption(isoCode: 'AS', name: 'American Samoa', dialCode: '+1-684'),
  CountryCodeOption(isoCode: 'AD', name: 'Andorra', dialCode: '+376'),
  CountryCodeOption(isoCode: 'AO', name: 'Angola', dialCode: '+244'),
  CountryCodeOption(isoCode: 'AI', name: 'Anguilla', dialCode: '+1-264'),
  CountryCodeOption(isoCode: 'AQ', name: 'Antarctica', dialCode: '+672'),
  CountryCodeOption(isoCode: 'AG', name: 'Antigua and Barbuda', dialCode: '+1-268'),
  CountryCodeOption(isoCode: 'AR', name: 'Argentina', dialCode: '+54'),
  CountryCodeOption(isoCode: 'AM', name: 'Armenia', dialCode: '+374'),
  CountryCodeOption(isoCode: 'AW', name: 'Aruba', dialCode: '+297'),
  CountryCodeOption(isoCode: 'AU', name: 'Australia', dialCode: '+61'),
  CountryCodeOption(isoCode: 'AT', name: 'Austria', dialCode: '+43'),
  CountryCodeOption(isoCode: 'AZ', name: 'Azerbaijan', dialCode: '+994'),
  CountryCodeOption(isoCode: 'BS', name: 'Bahamas', dialCode: '+1-242'),
  CountryCodeOption(isoCode: 'BH', name: 'Bahrain', dialCode: '+973'),
  CountryCodeOption(isoCode: 'BD', name: 'Bangladesh', dialCode: '+880'),
  CountryCodeOption(isoCode: 'BB', name: 'Barbados', dialCode: '+1-246'),
  CountryCodeOption(isoCode: 'BY', name: 'Belarus', dialCode: '+375'),
  CountryCodeOption(isoCode: 'BE', name: 'Belgium', dialCode: '+32'),
  CountryCodeOption(isoCode: 'BZ', name: 'Belize', dialCode: '+501'),
  CountryCodeOption(isoCode: 'BJ', name: 'Benin', dialCode: '+229'),
  CountryCodeOption(isoCode: 'BM', name: 'Bermuda', dialCode: '+1-441'),
  CountryCodeOption(isoCode: 'BT', name: 'Bhutan', dialCode: '+975'),
  CountryCodeOption(isoCode: 'BO', name: 'Bolivia (Plurinational State of)', dialCode: '+591'),
  CountryCodeOption(isoCode: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', dialCode: '+599'),
  CountryCodeOption(isoCode: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387'),
  CountryCodeOption(isoCode: 'BW', name: 'Botswana', dialCode: '+267'),
  CountryCodeOption(isoCode: 'BV', name: 'Bouvet Island', dialCode: '+47'),
  CountryCodeOption(isoCode: 'BR', name: 'Brazil', dialCode: '+55'),
  CountryCodeOption(isoCode: 'IO', name: 'British Indian Ocean Territory', dialCode: '+246'),
  CountryCodeOption(isoCode: 'VG', name: 'British Virgin Islands', dialCode: '+1-284'),
  CountryCodeOption(isoCode: 'BN', name: 'Brunei Darussalam', dialCode: '+673'),
  CountryCodeOption(isoCode: 'BG', name: 'Bulgaria', dialCode: '+359'),
  CountryCodeOption(isoCode: 'BF', name: 'Burkina Faso', dialCode: '+226'),
  CountryCodeOption(isoCode: 'BI', name: 'Burundi', dialCode: '+257'),
  CountryCodeOption(isoCode: 'CV', name: 'Cabo Verde', dialCode: '+238'),
  CountryCodeOption(isoCode: 'KH', name: 'Cambodia', dialCode: '+855'),
  CountryCodeOption(isoCode: 'CM', name: 'Cameroon', dialCode: '+237'),
  CountryCodeOption(isoCode: 'CA', name: 'Canada', dialCode: '+1'),
  CountryCodeOption(isoCode: 'KY', name: 'Cayman Islands', dialCode: '+1-345'),
  CountryCodeOption(isoCode: 'CF', name: 'Central African Republic', dialCode: '+236'),
  CountryCodeOption(isoCode: 'TD', name: 'Chad', dialCode: '+235'),
  CountryCodeOption(isoCode: 'CL', name: 'Chile', dialCode: '+56'),
  CountryCodeOption(isoCode: 'CN', name: 'China', dialCode: '+86'),
  CountryCodeOption(isoCode: 'HK', name: 'China, Hong Kong Special Administrative Region', dialCode: '+852'),
  CountryCodeOption(isoCode: 'MO', name: 'China, Macao Special Administrative Region', dialCode: '+853'),
  CountryCodeOption(isoCode: 'CX', name: 'Christmas Island', dialCode: '+61'),
  CountryCodeOption(isoCode: 'CC', name: 'Cocos (Keeling) Islands', dialCode: '+61'),
  CountryCodeOption(isoCode: 'CO', name: 'Colombia', dialCode: '+57'),
  CountryCodeOption(isoCode: 'KM', name: 'Comoros', dialCode: '+269'),
  CountryCodeOption(isoCode: 'CG', name: 'Congo', dialCode: '+242'),
  CountryCodeOption(isoCode: 'CK', name: 'Cook Islands', dialCode: '+682'),
  CountryCodeOption(isoCode: 'CR', name: 'Costa Rica', dialCode: '+506'),
  CountryCodeOption(isoCode: 'HR', name: 'Croatia', dialCode: '+385'),
  CountryCodeOption(isoCode: 'CU', name: 'Cuba', dialCode: '+53'),
  CountryCodeOption(isoCode: 'CW', name: 'Curacao', dialCode: '+599'),
  CountryCodeOption(isoCode: 'CY', name: 'Cyprus', dialCode: '+357'),
  CountryCodeOption(isoCode: 'CZ', name: 'Czechia', dialCode: '+420'),
  CountryCodeOption(isoCode: 'KP', name: 'Democratic People\'s Republic of Korea', dialCode: '+850'),
  CountryCodeOption(isoCode: 'CD', name: 'Democratic Republic of the Congo', dialCode: '+243'),
  CountryCodeOption(isoCode: 'DK', name: 'Denmark', dialCode: '+45'),
  CountryCodeOption(isoCode: 'DJ', name: 'Djibouti', dialCode: '+253'),
  CountryCodeOption(isoCode: 'DM', name: 'Dominica', dialCode: '+1-767'),
  CountryCodeOption(isoCode: 'DO', name: 'Dominican Republic', dialCode: '+1-809'),
  CountryCodeOption(isoCode: 'DO', name: 'Dominican Republic', dialCode: '+1-829'),
  CountryCodeOption(isoCode: 'DO', name: 'Dominican Republic', dialCode: '+1-849'),
  CountryCodeOption(isoCode: 'EC', name: 'Ecuador', dialCode: '+593'),
  CountryCodeOption(isoCode: 'EG', name: 'Egypt', dialCode: '+20'),
  CountryCodeOption(isoCode: 'SV', name: 'El Salvador', dialCode: '+503'),
  CountryCodeOption(isoCode: 'GQ', name: 'Equatorial Guinea', dialCode: '+240'),
  CountryCodeOption(isoCode: 'ER', name: 'Eritrea', dialCode: '+291'),
  CountryCodeOption(isoCode: 'EE', name: 'Estonia', dialCode: '+372'),
  CountryCodeOption(isoCode: 'SZ', name: 'Eswatini', dialCode: '+268'),
  CountryCodeOption(isoCode: 'ET', name: 'Ethiopia', dialCode: '+251'),
  CountryCodeOption(isoCode: 'FK', name: 'Falkland Islands', dialCode: '+500'),
  CountryCodeOption(isoCode: 'FO', name: 'Faroe Islands', dialCode: '+298'),
  CountryCodeOption(isoCode: 'FJ', name: 'Fiji', dialCode: '+679'),
  CountryCodeOption(isoCode: 'FI', name: 'Finland', dialCode: '+358'),
  CountryCodeOption(isoCode: 'FR', name: 'France', dialCode: '+33'),
  CountryCodeOption(isoCode: 'GF', name: 'French Guiana', dialCode: '+594'),
  CountryCodeOption(isoCode: 'PF', name: 'French Polynesia', dialCode: '+689'),
  CountryCodeOption(isoCode: 'TF', name: 'French Southern Territories', dialCode: '+262'),
  CountryCodeOption(isoCode: 'GA', name: 'Gabon', dialCode: '+241'),
  CountryCodeOption(isoCode: 'GM', name: 'Gambia', dialCode: '+220'),
  CountryCodeOption(isoCode: 'GE', name: 'Georgia', dialCode: '+995'),
  CountryCodeOption(isoCode: 'DE', name: 'Germany', dialCode: '+49'),
  CountryCodeOption(isoCode: 'GH', name: 'Ghana', dialCode: '+233'),
  CountryCodeOption(isoCode: 'GI', name: 'Gibraltar', dialCode: '+350'),
  CountryCodeOption(isoCode: 'GR', name: 'Greece', dialCode: '+30'),
  CountryCodeOption(isoCode: 'GL', name: 'Greenland', dialCode: '+299'),
  CountryCodeOption(isoCode: 'GD', name: 'Grenada', dialCode: '+1-473'),
  CountryCodeOption(isoCode: 'GP', name: 'Guadeloupe', dialCode: '+590'),
  CountryCodeOption(isoCode: 'GU', name: 'Guam', dialCode: '+1-671'),
  CountryCodeOption(isoCode: 'GT', name: 'Guatemala', dialCode: '+502'),
  CountryCodeOption(isoCode: 'GG', name: 'Guernsey', dialCode: '+44'),
  CountryCodeOption(isoCode: 'GN', name: 'Guinea', dialCode: '+224'),
  CountryCodeOption(isoCode: 'GW', name: 'Guinea-Bissau', dialCode: '+245'),
  CountryCodeOption(isoCode: 'GY', name: 'Guyana', dialCode: '+592'),
  CountryCodeOption(isoCode: 'HT', name: 'Haiti', dialCode: '+509'),
  CountryCodeOption(isoCode: 'HM', name: 'Heard Island and McDonald Islands', dialCode: '+672'),
  CountryCodeOption(isoCode: 'VA', name: 'Holy See', dialCode: '+39-06'),
  CountryCodeOption(isoCode: 'HN', name: 'Honduras', dialCode: '+504'),
  CountryCodeOption(isoCode: 'HU', name: 'Hungary', dialCode: '+36'),
  CountryCodeOption(isoCode: 'IS', name: 'Iceland', dialCode: '+354'),
  CountryCodeOption(isoCode: 'IN', name: 'India', dialCode: '+91'),
  CountryCodeOption(isoCode: 'ID', name: 'Indonesia', dialCode: '+62'),
  CountryCodeOption(isoCode: 'IR', name: 'Iran (Islamic Republic of)', dialCode: '+98'),
  CountryCodeOption(isoCode: 'IQ', name: 'Iraq', dialCode: '+964'),
  CountryCodeOption(isoCode: 'IE', name: 'Ireland', dialCode: '+353'),
  CountryCodeOption(isoCode: 'IM', name: 'Isle of Man', dialCode: '+44'),
  CountryCodeOption(isoCode: 'IL', name: 'Israel', dialCode: '+972'),
  CountryCodeOption(isoCode: 'IT', name: 'Italy', dialCode: '+39'),
  CountryCodeOption(isoCode: 'CI', name: 'Ivory Coast', dialCode: '+225'),
  CountryCodeOption(isoCode: 'JM', name: 'Jamaica', dialCode: '+1-876'),
  CountryCodeOption(isoCode: 'JP', name: 'Japan', dialCode: '+81'),
  CountryCodeOption(isoCode: 'JE', name: 'Jersey', dialCode: '+44'),
  CountryCodeOption(isoCode: 'JO', name: 'Jordan', dialCode: '+962'),
  CountryCodeOption(isoCode: 'KZ', name: 'Kazakhstan', dialCode: '+7'),
  CountryCodeOption(isoCode: 'KE', name: 'Kenya', dialCode: '+254'),
  CountryCodeOption(isoCode: 'KI', name: 'Kiribati', dialCode: '+686'),
  CountryCodeOption(isoCode: 'KW', name: 'Kuwait', dialCode: '+965'),
  CountryCodeOption(isoCode: 'KG', name: 'Kyrgyzstan', dialCode: '+996'),
  CountryCodeOption(isoCode: 'LA', name: 'Lao People\'s Democratic Republic', dialCode: '+856'),
  CountryCodeOption(isoCode: 'LV', name: 'Latvia', dialCode: '+371'),
  CountryCodeOption(isoCode: 'LB', name: 'Lebanon', dialCode: '+961'),
  CountryCodeOption(isoCode: 'LS', name: 'Lesotho', dialCode: '+266'),
  CountryCodeOption(isoCode: 'LR', name: 'Liberia', dialCode: '+231'),
  CountryCodeOption(isoCode: 'LY', name: 'Libya', dialCode: '+218'),
  CountryCodeOption(isoCode: 'LI', name: 'Liechtenstein', dialCode: '+423'),
  CountryCodeOption(isoCode: 'LT', name: 'Lithuania', dialCode: '+370'),
  CountryCodeOption(isoCode: 'LU', name: 'Luxembourg', dialCode: '+352'),
  CountryCodeOption(isoCode: 'MG', name: 'Madagascar', dialCode: '+261'),
  CountryCodeOption(isoCode: 'MW', name: 'Malawi', dialCode: '+265'),
  CountryCodeOption(isoCode: 'MY', name: 'Malaysia', dialCode: '+60'),
  CountryCodeOption(isoCode: 'MV', name: 'Maldives', dialCode: '+960'),
  CountryCodeOption(isoCode: 'ML', name: 'Mali', dialCode: '+223'),
  CountryCodeOption(isoCode: 'MT', name: 'Malta', dialCode: '+356'),
  CountryCodeOption(isoCode: 'MH', name: 'Marshall Islands', dialCode: '+692'),
  CountryCodeOption(isoCode: 'MQ', name: 'Martinique', dialCode: '+596'),
  CountryCodeOption(isoCode: 'MR', name: 'Mauritania', dialCode: '+222'),
  CountryCodeOption(isoCode: 'MU', name: 'Mauritius', dialCode: '+230'),
  CountryCodeOption(isoCode: 'YT', name: 'Mayotte', dialCode: '+262'),
  CountryCodeOption(isoCode: 'MX', name: 'Mexico', dialCode: '+52'),
  CountryCodeOption(isoCode: 'FM', name: 'Micronesia (Federated States of)', dialCode: '+691'),
  CountryCodeOption(isoCode: 'MC', name: 'Monaco', dialCode: '+377'),
  CountryCodeOption(isoCode: 'MN', name: 'Mongolia', dialCode: '+976'),
  CountryCodeOption(isoCode: 'ME', name: 'Montenegro', dialCode: '+382'),
  CountryCodeOption(isoCode: 'MS', name: 'Montserrat', dialCode: '+1-664'),
  CountryCodeOption(isoCode: 'MA', name: 'Morocco', dialCode: '+212'),
  CountryCodeOption(isoCode: 'MZ', name: 'Mozambique', dialCode: '+258'),
  CountryCodeOption(isoCode: 'MM', name: 'Myanmar', dialCode: '+95'),
  CountryCodeOption(isoCode: 'NA', name: 'Namibia', dialCode: '+264'),
  CountryCodeOption(isoCode: 'NR', name: 'Nauru', dialCode: '+674'),
  CountryCodeOption(isoCode: 'NP', name: 'Nepal', dialCode: '+977'),
  CountryCodeOption(isoCode: 'NL', name: 'Netherlands', dialCode: '+31'),
  CountryCodeOption(isoCode: 'NC', name: 'New Caledonia', dialCode: '+687'),
  CountryCodeOption(isoCode: 'NZ', name: 'New Zealand', dialCode: '+64'),
  CountryCodeOption(isoCode: 'NI', name: 'Nicaragua', dialCode: '+505'),
  CountryCodeOption(isoCode: 'NE', name: 'Niger', dialCode: '+227'),
  CountryCodeOption(isoCode: 'NG', name: 'Nigeria', dialCode: '+234'),
  CountryCodeOption(isoCode: 'NU', name: 'Niue', dialCode: '+683'),
  CountryCodeOption(isoCode: 'NF', name: 'Norfolk Island', dialCode: '+672'),
  CountryCodeOption(isoCode: 'MK', name: 'North Macedonia', dialCode: '+389'),
  CountryCodeOption(isoCode: 'MP', name: 'Northern Mariana Islands', dialCode: '+1-670'),
  CountryCodeOption(isoCode: 'NO', name: 'Norway', dialCode: '+47'),
  CountryCodeOption(isoCode: 'OM', name: 'Oman', dialCode: '+968'),
  CountryCodeOption(isoCode: 'PK', name: 'Pakistan', dialCode: '+92'),
  CountryCodeOption(isoCode: 'PW', name: 'Palau', dialCode: '+680'),
  CountryCodeOption(isoCode: 'PA', name: 'Panama', dialCode: '+507'),
  CountryCodeOption(isoCode: 'PG', name: 'Papua New Guinea', dialCode: '+675'),
  CountryCodeOption(isoCode: 'PY', name: 'Paraguay', dialCode: '+595'),
  CountryCodeOption(isoCode: 'PE', name: 'Peru', dialCode: '+51'),
  CountryCodeOption(isoCode: 'PH', name: 'Philippines', dialCode: '+63'),
  CountryCodeOption(isoCode: 'PN', name: 'Pitcairn', dialCode: '+870'),
  CountryCodeOption(isoCode: 'PL', name: 'Poland', dialCode: '+48'),
  CountryCodeOption(isoCode: 'PT', name: 'Portugal', dialCode: '+351'),
  CountryCodeOption(isoCode: 'PR', name: 'Puerto Rico', dialCode: '+1'),
  CountryCodeOption(isoCode: 'QA', name: 'Qatar', dialCode: '+974'),
  CountryCodeOption(isoCode: 'KR', name: 'Republic of Korea', dialCode: '+82'),
  CountryCodeOption(isoCode: 'MD', name: 'Republic of Moldova', dialCode: '+373'),
  CountryCodeOption(isoCode: 'RE', name: 'Reunion', dialCode: '+262'),
  CountryCodeOption(isoCode: 'RO', name: 'Romania', dialCode: '+40'),
  CountryCodeOption(isoCode: 'RU', name: 'Russian Federation', dialCode: '+7'),
  CountryCodeOption(isoCode: 'RW', name: 'Rwanda', dialCode: '+250'),
  CountryCodeOption(isoCode: 'BL', name: 'Saint Barthelemy', dialCode: '+590'),
  CountryCodeOption(isoCode: 'SH', name: 'Saint Helena', dialCode: '+290 n'),
  CountryCodeOption(isoCode: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1-869'),
  CountryCodeOption(isoCode: 'LC', name: 'Saint Lucia', dialCode: '+1-758'),
  CountryCodeOption(isoCode: 'MF', name: 'Saint Martin (French Part)', dialCode: '+590'),
  CountryCodeOption(isoCode: 'PM', name: 'Saint Pierre and Miquelon', dialCode: '+508'),
  CountryCodeOption(isoCode: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1-784'),
  CountryCodeOption(isoCode: 'WS', name: 'Samoa', dialCode: '+685'),
  CountryCodeOption(isoCode: 'SM', name: 'San Marino', dialCode: '+378'),
  CountryCodeOption(isoCode: 'ST', name: 'Sao Tome and Principe', dialCode: '+239'),
  CountryCodeOption(isoCode: 'SA', name: 'Saudi Arabia', dialCode: '+966'),
  CountryCodeOption(isoCode: 'SN', name: 'Senegal', dialCode: '+221'),
  CountryCodeOption(isoCode: 'RS', name: 'Serbia', dialCode: '+381 p'),
  CountryCodeOption(isoCode: 'SC', name: 'Seychelles', dialCode: '+248'),
  CountryCodeOption(isoCode: 'SL', name: 'Sierra Leone', dialCode: '+232'),
  CountryCodeOption(isoCode: 'SG', name: 'Singapore', dialCode: '+65'),
  CountryCodeOption(isoCode: 'SX', name: 'Sint Maarten (Dutch part)', dialCode: '+1-721'),
  CountryCodeOption(isoCode: 'SK', name: 'Slovakia', dialCode: '+421'),
  CountryCodeOption(isoCode: 'SI', name: 'Slovenia', dialCode: '+386'),
  CountryCodeOption(isoCode: 'SB', name: 'Solomon Islands', dialCode: '+677'),
  CountryCodeOption(isoCode: 'SO', name: 'Somalia', dialCode: '+252'),
  CountryCodeOption(isoCode: 'ZA', name: 'South Africa', dialCode: '+27'),
  CountryCodeOption(isoCode: 'GS', name: 'South Georgia and the South Sandwich Islands', dialCode: '+500'),
  CountryCodeOption(isoCode: 'SS', name: 'South Sudan', dialCode: '+211'),
  CountryCodeOption(isoCode: 'ES', name: 'Spain', dialCode: '+34'),
  CountryCodeOption(isoCode: 'LK', name: 'Sri Lanka', dialCode: '+94'),
  CountryCodeOption(isoCode: 'PS', name: 'State of Palestine', dialCode: '+970'),
  CountryCodeOption(isoCode: 'SD', name: 'Sudan', dialCode: '+249'),
  CountryCodeOption(isoCode: 'SR', name: 'Suriname', dialCode: '+597'),
  CountryCodeOption(isoCode: 'SJ', name: 'Svalbard and Jan Mayen Islands', dialCode: '+47'),
  CountryCodeOption(isoCode: 'SE', name: 'Sweden', dialCode: '+46'),
  CountryCodeOption(isoCode: 'CH', name: 'Switzerland', dialCode: '+41'),
  CountryCodeOption(isoCode: 'SY', name: 'Syrian Arab Republic', dialCode: '+963'),
  CountryCodeOption(isoCode: 'TW', name: 'Taiwan', dialCode: '+886'),
  CountryCodeOption(isoCode: 'TJ', name: 'Tajikistan', dialCode: '+992'),
  CountryCodeOption(isoCode: 'TH', name: 'Thailand', dialCode: '+66'),
  CountryCodeOption(isoCode: 'TL', name: 'Timor-Leste', dialCode: '+670'),
  CountryCodeOption(isoCode: 'TG', name: 'Togo', dialCode: '+228'),
  CountryCodeOption(isoCode: 'TK', name: 'Tokelau', dialCode: '+690'),
  CountryCodeOption(isoCode: 'TO', name: 'Tonga', dialCode: '+676'),
  CountryCodeOption(isoCode: 'TT', name: 'Trinidad and Tobago', dialCode: '+1-868'),
  CountryCodeOption(isoCode: 'TN', name: 'Tunisia', dialCode: '+216'),
  CountryCodeOption(isoCode: 'TR', name: 'Turkey', dialCode: '+90'),
  CountryCodeOption(isoCode: 'TM', name: 'Turkmenistan', dialCode: '+993'),
  CountryCodeOption(isoCode: 'TC', name: 'Turks and Caicos Islands', dialCode: '+1-649'),
  CountryCodeOption(isoCode: 'TV', name: 'Tuvalu', dialCode: '+688'),
  CountryCodeOption(isoCode: 'UG', name: 'Uganda', dialCode: '+256'),
  CountryCodeOption(isoCode: 'UA', name: 'Ukraine', dialCode: '+380'),
  CountryCodeOption(isoCode: 'AE', name: 'United Arab Emirates', dialCode: '+971'),
  CountryCodeOption(isoCode: 'GB', name: 'United Kingdom of Great Britain and Northern Ireland', dialCode: '+44'),
  CountryCodeOption(isoCode: 'TZ', name: 'United Republic of Tanzania', dialCode: '+255'),
  CountryCodeOption(isoCode: 'US', name: 'United States of America', dialCode: '+1'),
  CountryCodeOption(isoCode: 'VI', name: 'United States Virgin Islands', dialCode: '+1-340'),
  CountryCodeOption(isoCode: 'UY', name: 'Uruguay', dialCode: '+598'),
  CountryCodeOption(isoCode: 'UZ', name: 'Uzbekistan', dialCode: '+998'),
  CountryCodeOption(isoCode: 'VU', name: 'Vanuatu', dialCode: '+678'),
  CountryCodeOption(isoCode: 'VE', name: 'Venezuela (Bolivarian Republic of)', dialCode: '+58'),
  CountryCodeOption(isoCode: 'VN', name: 'Viet Nam', dialCode: '+84'),
  CountryCodeOption(isoCode: 'WF', name: 'Wallis and Futuna Islands', dialCode: '+681'),
  CountryCodeOption(isoCode: 'EH', name: 'Western Sahara', dialCode: '+212'),
  CountryCodeOption(isoCode: 'YE', name: 'Yemen', dialCode: '+967'),
  CountryCodeOption(isoCode: 'ZM', name: 'Zambia', dialCode: '+260'),
  CountryCodeOption(isoCode: 'ZW', name: 'Zimbabwe', dialCode: '+263'),
];

const String defaultCountryCodeId = 'IN|+91';

CountryCodeOption? countryCodeOptionById(String? id) {
  if (id == null) {
    return null;
  }
  for (final option in countryCodeOptions) {
    if (option.id == id) {
      return option;
    }
  }
  return null;
}


